---
branches:
  - name: main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      parserOpts:
        noteKeywords: ["BREAKING CHANGE", "BREAKING CHANGES"]
      releaseRules:
        - breaking: true
          release: major
        - revert: true
          release: patch
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: chore
          release: false
        - type: docs
          release: false
        - type: test
          release: false
        - type: tests
          release: false
        - # if a commit type is missing, default to a minor release (i.e. assume feat:)
          # Note that dependabot has its own rule which shouldn't be overwritten by this
          # which is why we're explicitly disallowing its commits. The release bot's commits
          # wouldn't be matched here and it sets the release to false which always takes
          # the highest precedence anyway
          type: null
          release: minor
          author:
            name: "!dependabot[bot]"
        - # the commits generated by dependabot should be patch releases
          author:
            name: dependabot[bot]
          release: patch
        - # the commits generated by the release bot shouldn't generate a new release
          author:
            name: semantic-release-bot
          release: false
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: |-
        # Changelog
  
        All notable changes to this project will be documented in this file.
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      message: |-
        chore(release): version ${nextRelease.version} [skip ci]
  
        ${nextRelease.notes}
  - "@semantic-release/github"

repositoryUrl: https://github.com/Afinsky/terraform-aws-codepipeline
ci: true
